

# Code Generated by Sidekick is for learning and experimentation purposes only
from pydantic import BaseModel
from typing import List, Optional

class UserBase(BaseModel):
    email: str

class UserCreate(UserBase):
    password: str

class User(UserBase):
    id: int

    class Config:
        orm_mode = True

class UserLogin(BaseModel):
    email: str
    password: str

class RecipeBase(BaseModel):
    title: str
    image: str
    instructions: str

class RecipeCreate(RecipeBase):
    pass

class Recipe(RecipeBase):
    id: int
    owner_id: int

    class Config:
        orm_mode = True

class SpoonacularRecipe(BaseModel):
    id: int
    title: str
    image: str
    instructions: Optional[str] = "Instructions not available in this endpoint"

    class Config:
        orm_mode = True









